CREATE DATABASE WINNCHAY;
	USE WINNCHAY;

CREATE TABLE CATEGORIES(
	IDCATEGORY INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CATEGORY VARCHAR(25) NOT NULL,

	CONSTRAINT UQ_CATEGORY UNIQUE (CATEGORY)
);

CREATE TABLE PLATFORMS(
	IDPLATFORM INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PLATFORM VARCHAR(20) NOT NULL,

	CONSTRAINT UQ_PLATFORM UNIQUE (PLATFORM)
);

CREATE TABLE PICTURES(
	IDPICTURE INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PICTURE VARCHAR(10)
);

CREATE TABLE PROFILE_PICTURES(
	IDPROFILE INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PICTURE VARCHAR(10) NOT NULL
);

CREATE TABLE PLAYERS(
	IDPLAYER INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	IDPROFILE INT(11),
	FIRST_NAME VARCHAR(20) NOT NULL,
	LAST_NAME VARCHAR(20) NOT NULL,
	USERNAME VARCHAR(16) NOT NULL,
	EMAIL VARCHAR(30) NOT NULL,
	PASSWORD VARCHAR(16) NOT NULL,
	TEAM VARCHAR(16),
	CPF INT(11),
	
	CONSTRAINT UQ_EMAIL_PLAYERS UNIQUE (EMAIL),
	CONSTRAINT UQ_CPF_PLAYERS UNIQUE (CPF),
	CONSTRAINT UQ_USERNAME_PLAYERS UNIQUE (USERNAME),
	CONSTRAINT FK_PICPROFILE_PLAYERS FOREIGN KEY (IDPROFILE) REFERENCES PROFILE_PICTURE (IDPROFILE)
);

CREATE TABLE RANKING_FIFA(
	IDRKG_FIFA INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	IDPLAYER INT(11) NOT NULL,
	IDPLATFORM INT(11) NOT NULL, 

	CONSTRAINT FK_IDPLATFORM_RKGFIFA FOREIGN KEY (IDPLATFORM) REFERENCES PLATFORMS (IDPLATFORM)
);

INSERT INTO PLATFORMS VALUES ('PC');
INSERT INTO PLATFORMS VALUES ('PS4');
INSERT INTO PLATFORMS VALUES ('XBOX');

INSERT INTO CATEGORIES VALUES ('FIFA 2020');
INSERT INTO CATEGORIES VALUES ('PES 2020');